#!/bin/bash
# Install brave-browser using an install script
# Fetch the source from the upstream repo and download it on the user machine
set -euo pipefail
IFS=$'\n\t'

# Change to temporary directory
cd $(mktemp -d)

echo 'Installing build dependencies...'
echo 'Adding trusted signed key...'
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo 'Adding upstream source to local sources...'
echo 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list'

echo 'Updating sources...' 
sudo apt update

echo 'Run the command sudo apt install brave-browser to install Brave Browser'
